./error_fun_ret.nit:17,1--13: Control error: Reached end of function (a 'return' with a value was expected).
