error_init_auto.nit:34,5--7: Error: expected 1 argument(s) for `autoinit(x: Int)`; got 0. See introduction at `error_init_auto::A::autoinit`.
error_init_auto.nit:36,5--7: Error: expected 1 argument(s) for `autoinit(x: Int)`; got 2. See introduction at `error_init_auto::A::autoinit`.
error_init_auto.nit:37,5--7: Error: expected 1 argument(s) for `autoinit(x: Int)`; got 3. See introduction at `error_init_auto::A::autoinit`.
error_init_auto.nit:38,11--13: Error: method `foo` does not exists in `A`.
