./error_ref_fun.nit:20,2--13: Control error: Reached end of function (a 'return' with a value was expected).
